name: Windows FLTK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.29.2' # or latest stable

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install FLTK with vcpkg
      run: .\vcpkg\vcpkg.exe install fltk:x64-windows

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: todo-fltk-exe
        path: build\Release\*.exe
