name: Build FLTK App for Windows

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@v3

    - name: Build and Install FLTK from source
      run: |
        git clone https://github.com/fltk/fltk.git
        cd fltk
        git checkout release-1.3.5
        cmake -B build -S . -DOPTION_BUILD_EXAMPLES=OFF
        cmake --build build --config Release
        cmake --install build --prefix C:/fltk

    - name: Configure your C++ Project
      run: |
        cmake -B build -S todo-fltk -DCMAKE_PREFIX_PATH="C:/fltk"

    - name: Build your C++ Project
      run: cmake --build build --config Release

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: todo-windows-exe
        path: build/Release/*.exe
